### ISSUE TITLE
failed on npm start

### ISSUE THREAD

**Issue by Pendragon0988** [hotforfeature/angular-polymer-starter-kit#1]
here's some parts of the error message emitted while launching for dev

![image](https://user-images.githubusercontent.com/8242751/32453337-e58ccc9a-c356-11e7-8740-a8a25a143e80.png)
![image](https://user-images.githubusercontent.com/8242751/32453364-f1a63548-c356-11e7-8b06-6f3bc533fe4f.png)

**Comment by hotforfeature** [comment]
Looks like the `patch-cli.js` script did not run. Try re-running it with `npm run postinstall`

**Comment by Pendragon0988** [comment]
awesomesauce! just saw your latest commit and update on the readme and it works like a charm :)
I wonder what's causing it I thought it has something to do with my typescript version nonetheless thanks for this great fusion :) 💯

**Comment by hotforfeature** [comment]
`postinstall` should always run whenever you do `npm install`, but it doesn't run when updating individual packages. The CLI may be updated or restored itself and the postinstall script didn't patch it.

Gonna close this as fixed :)
