### ISSUE TITLE
Unable the run the app using ng serve --app es5

### ISSUE THREAD

**Issue by sansantosh** [hotforfeature/angular-polymer-starter-kit#7]
zone.js:690 Unhandled Promise rejection: Cannot read property 'call' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (inline.bundle.js:55)

**Comment by hotforfeature** [comment]
Looks like the problem was with webpack's dynamic import not working that well with the Angular CLI. I changed it back to a basic require to fix it.
